import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Panicker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body className="lg:text-[3rem] text-[1.5rem] cursor-crosshair">
        {children}
      </body>
    </html>
  );
}
